name: Node.js Package
on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Select the version bump type'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major
permissions: write-all
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config --global user.email "gkr@tuta.io"
          git config --global user.name "gkr-bot"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.version-bump }}
          git tag -a $(node -p "require('./package.json').version") -m "Version $(node -p "require('./package.json').version")"
          git push origin HEAD --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
